/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SkillsIndexRouteImport } from './routes/skills/index'
import { Route as ProfilesIndexRouteImport } from './routes/profiles/index'
import { Route as ProfileGroupsIndexRouteImport } from './routes/profile-groups/index'
import { Route as GroupsIndexRouteImport } from './routes/groups/index'
import { Route as ConfigIndexRouteImport } from './routes/config/index'
import { Route as AgentsIndexRouteImport } from './routes/agents/index'
import { Route as ProfilesIdRouteImport } from './routes/profiles/$id'
import { Route as ProfileGroupsIdRouteImport } from './routes/profile-groups/$id'
import { Route as ConfigTokensRouteImport } from './routes/config/tokens'
import { Route as ConfigServicesRouteImport } from './routes/config/services'
import { Route as ApiSplatRouteImport } from './routes/api/$'
import { Route as GroupsIdIndexRouteImport } from './routes/groups/$id/index'
import { Route as AgentsIdIndexRouteImport } from './routes/agents/$id/index'
import { Route as GroupsIdMemoryRouteImport } from './routes/groups/$id/memory'
import { Route as AgentsIdTriggersRouteImport } from './routes/agents/$id/triggers'
import { Route as AgentsIdInboxRouteImport } from './routes/agents/$id/inbox'

const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillsIndexRoute = SkillsIndexRouteImport.update({
  id: '/skills/',
  path: '/skills/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilesIndexRoute = ProfilesIndexRouteImport.update({
  id: '/profiles/',
  path: '/profiles/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileGroupsIndexRoute = ProfileGroupsIndexRouteImport.update({
  id: '/profile-groups/',
  path: '/profile-groups/',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupsIndexRoute = GroupsIndexRouteImport.update({
  id: '/groups/',
  path: '/groups/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfigIndexRoute = ConfigIndexRouteImport.update({
  id: '/config/',
  path: '/config/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsIndexRoute = AgentsIndexRouteImport.update({
  id: '/agents/',
  path: '/agents/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilesIdRoute = ProfilesIdRouteImport.update({
  id: '/profiles/$id',
  path: '/profiles/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileGroupsIdRoute = ProfileGroupsIdRouteImport.update({
  id: '/profile-groups/$id',
  path: '/profile-groups/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfigTokensRoute = ConfigTokensRouteImport.update({
  id: '/config/tokens',
  path: '/config/tokens',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfigServicesRoute = ConfigServicesRouteImport.update({
  id: '/config/services',
  path: '/config/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupsIdIndexRoute = GroupsIdIndexRouteImport.update({
  id: '/groups/$id/',
  path: '/groups/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsIdIndexRoute = AgentsIdIndexRouteImport.update({
  id: '/agents/$id/',
  path: '/agents/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupsIdMemoryRoute = GroupsIdMemoryRouteImport.update({
  id: '/groups/$id/memory',
  path: '/groups/$id/memory',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsIdTriggersRoute = AgentsIdTriggersRouteImport.update({
  id: '/agents/$id/triggers',
  path: '/agents/$id/triggers',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsIdInboxRoute = AgentsIdInboxRouteImport.update({
  id: '/agents/$id/inbox',
  path: '/agents/$id/inbox',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/welcome': typeof WelcomeRoute
  '/api/$': typeof ApiSplatRoute
  '/config/services': typeof ConfigServicesRoute
  '/config/tokens': typeof ConfigTokensRoute
  '/profile-groups/$id': typeof ProfileGroupsIdRoute
  '/profiles/$id': typeof ProfilesIdRoute
  '/agents/': typeof AgentsIndexRoute
  '/config/': typeof ConfigIndexRoute
  '/groups/': typeof GroupsIndexRoute
  '/profile-groups/': typeof ProfileGroupsIndexRoute
  '/profiles/': typeof ProfilesIndexRoute
  '/skills/': typeof SkillsIndexRoute
  '/agents/$id/inbox': typeof AgentsIdInboxRoute
  '/agents/$id/triggers': typeof AgentsIdTriggersRoute
  '/groups/$id/memory': typeof GroupsIdMemoryRoute
  '/agents/$id/': typeof AgentsIdIndexRoute
  '/groups/$id/': typeof GroupsIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/welcome': typeof WelcomeRoute
  '/api/$': typeof ApiSplatRoute
  '/config/services': typeof ConfigServicesRoute
  '/config/tokens': typeof ConfigTokensRoute
  '/profile-groups/$id': typeof ProfileGroupsIdRoute
  '/profiles/$id': typeof ProfilesIdRoute
  '/agents': typeof AgentsIndexRoute
  '/config': typeof ConfigIndexRoute
  '/groups': typeof GroupsIndexRoute
  '/profile-groups': typeof ProfileGroupsIndexRoute
  '/profiles': typeof ProfilesIndexRoute
  '/skills': typeof SkillsIndexRoute
  '/agents/$id/inbox': typeof AgentsIdInboxRoute
  '/agents/$id/triggers': typeof AgentsIdTriggersRoute
  '/groups/$id/memory': typeof GroupsIdMemoryRoute
  '/agents/$id': typeof AgentsIdIndexRoute
  '/groups/$id': typeof GroupsIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/welcome': typeof WelcomeRoute
  '/api/$': typeof ApiSplatRoute
  '/config/services': typeof ConfigServicesRoute
  '/config/tokens': typeof ConfigTokensRoute
  '/profile-groups/$id': typeof ProfileGroupsIdRoute
  '/profiles/$id': typeof ProfilesIdRoute
  '/agents/': typeof AgentsIndexRoute
  '/config/': typeof ConfigIndexRoute
  '/groups/': typeof GroupsIndexRoute
  '/profile-groups/': typeof ProfileGroupsIndexRoute
  '/profiles/': typeof ProfilesIndexRoute
  '/skills/': typeof SkillsIndexRoute
  '/agents/$id/inbox': typeof AgentsIdInboxRoute
  '/agents/$id/triggers': typeof AgentsIdTriggersRoute
  '/groups/$id/memory': typeof GroupsIdMemoryRoute
  '/agents/$id/': typeof AgentsIdIndexRoute
  '/groups/$id/': typeof GroupsIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/welcome'
    | '/api/$'
    | '/config/services'
    | '/config/tokens'
    | '/profile-groups/$id'
    | '/profiles/$id'
    | '/agents/'
    | '/config/'
    | '/groups/'
    | '/profile-groups/'
    | '/profiles/'
    | '/skills/'
    | '/agents/$id/inbox'
    | '/agents/$id/triggers'
    | '/groups/$id/memory'
    | '/agents/$id/'
    | '/groups/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/welcome'
    | '/api/$'
    | '/config/services'
    | '/config/tokens'
    | '/profile-groups/$id'
    | '/profiles/$id'
    | '/agents'
    | '/config'
    | '/groups'
    | '/profile-groups'
    | '/profiles'
    | '/skills'
    | '/agents/$id/inbox'
    | '/agents/$id/triggers'
    | '/groups/$id/memory'
    | '/agents/$id'
    | '/groups/$id'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/welcome'
    | '/api/$'
    | '/config/services'
    | '/config/tokens'
    | '/profile-groups/$id'
    | '/profiles/$id'
    | '/agents/'
    | '/config/'
    | '/groups/'
    | '/profile-groups/'
    | '/profiles/'
    | '/skills/'
    | '/agents/$id/inbox'
    | '/agents/$id/triggers'
    | '/groups/$id/memory'
    | '/agents/$id/'
    | '/groups/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  WelcomeRoute: typeof WelcomeRoute
  ApiSplatRoute: typeof ApiSplatRoute
  ConfigServicesRoute: typeof ConfigServicesRoute
  ConfigTokensRoute: typeof ConfigTokensRoute
  ProfileGroupsIdRoute: typeof ProfileGroupsIdRoute
  ProfilesIdRoute: typeof ProfilesIdRoute
  AgentsIndexRoute: typeof AgentsIndexRoute
  ConfigIndexRoute: typeof ConfigIndexRoute
  GroupsIndexRoute: typeof GroupsIndexRoute
  ProfileGroupsIndexRoute: typeof ProfileGroupsIndexRoute
  ProfilesIndexRoute: typeof ProfilesIndexRoute
  SkillsIndexRoute: typeof SkillsIndexRoute
  AgentsIdInboxRoute: typeof AgentsIdInboxRoute
  AgentsIdTriggersRoute: typeof AgentsIdTriggersRoute
  GroupsIdMemoryRoute: typeof GroupsIdMemoryRoute
  AgentsIdIndexRoute: typeof AgentsIdIndexRoute
  GroupsIdIndexRoute: typeof GroupsIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skills/': {
      id: '/skills/'
      path: '/skills'
      fullPath: '/skills/'
      preLoaderRoute: typeof SkillsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profiles/': {
      id: '/profiles/'
      path: '/profiles'
      fullPath: '/profiles/'
      preLoaderRoute: typeof ProfilesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile-groups/': {
      id: '/profile-groups/'
      path: '/profile-groups'
      fullPath: '/profile-groups/'
      preLoaderRoute: typeof ProfileGroupsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups/': {
      id: '/groups/'
      path: '/groups'
      fullPath: '/groups/'
      preLoaderRoute: typeof GroupsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/config/': {
      id: '/config/'
      path: '/config'
      fullPath: '/config/'
      preLoaderRoute: typeof ConfigIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/': {
      id: '/agents/'
      path: '/agents'
      fullPath: '/agents/'
      preLoaderRoute: typeof AgentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profiles/$id': {
      id: '/profiles/$id'
      path: '/profiles/$id'
      fullPath: '/profiles/$id'
      preLoaderRoute: typeof ProfilesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile-groups/$id': {
      id: '/profile-groups/$id'
      path: '/profile-groups/$id'
      fullPath: '/profile-groups/$id'
      preLoaderRoute: typeof ProfileGroupsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/config/tokens': {
      id: '/config/tokens'
      path: '/config/tokens'
      fullPath: '/config/tokens'
      preLoaderRoute: typeof ConfigTokensRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/config/services': {
      id: '/config/services'
      path: '/config/services'
      fullPath: '/config/services'
      preLoaderRoute: typeof ConfigServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups/$id/': {
      id: '/groups/$id/'
      path: '/groups/$id'
      fullPath: '/groups/$id/'
      preLoaderRoute: typeof GroupsIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/$id/': {
      id: '/agents/$id/'
      path: '/agents/$id'
      fullPath: '/agents/$id/'
      preLoaderRoute: typeof AgentsIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups/$id/memory': {
      id: '/groups/$id/memory'
      path: '/groups/$id/memory'
      fullPath: '/groups/$id/memory'
      preLoaderRoute: typeof GroupsIdMemoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/$id/triggers': {
      id: '/agents/$id/triggers'
      path: '/agents/$id/triggers'
      fullPath: '/agents/$id/triggers'
      preLoaderRoute: typeof AgentsIdTriggersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/$id/inbox': {
      id: '/agents/$id/inbox'
      path: '/agents/$id/inbox'
      fullPath: '/agents/$id/inbox'
      preLoaderRoute: typeof AgentsIdInboxRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  WelcomeRoute: WelcomeRoute,
  ApiSplatRoute: ApiSplatRoute,
  ConfigServicesRoute: ConfigServicesRoute,
  ConfigTokensRoute: ConfigTokensRoute,
  ProfileGroupsIdRoute: ProfileGroupsIdRoute,
  ProfilesIdRoute: ProfilesIdRoute,
  AgentsIndexRoute: AgentsIndexRoute,
  ConfigIndexRoute: ConfigIndexRoute,
  GroupsIndexRoute: GroupsIndexRoute,
  ProfileGroupsIndexRoute: ProfileGroupsIndexRoute,
  ProfilesIndexRoute: ProfilesIndexRoute,
  SkillsIndexRoute: SkillsIndexRoute,
  AgentsIdInboxRoute: AgentsIdInboxRoute,
  AgentsIdTriggersRoute: AgentsIdTriggersRoute,
  GroupsIdMemoryRoute: GroupsIdMemoryRoute,
  AgentsIdIndexRoute: AgentsIdIndexRoute,
  GroupsIdIndexRoute: GroupsIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
