/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TemplatesIndexRouteImport } from './routes/templates/index'
import { Route as TeamsIndexRouteImport } from './routes/teams/index'
import { Route as SkillsIndexRouteImport } from './routes/skills/index'
import { Route as ConfigIndexRouteImport } from './routes/config/index'
import { Route as ApprovalsIndexRouteImport } from './routes/approvals/index'
import { Route as AgentsIndexRouteImport } from './routes/agents/index'
import { Route as ConfigTokensRouteImport } from './routes/config/tokens'
import { Route as ConfigServicesRouteImport } from './routes/config/services'
import { Route as ConfigMcpRouteImport } from './routes/config/mcp'
import { Route as ApiSplatRouteImport } from './routes/api/$'
import { Route as TemplatesTeamsIndexRouteImport } from './routes/templates/teams/index'
import { Route as TemplatesAgentsIndexRouteImport } from './routes/templates/agents/index'
import { Route as TeamsIdIndexRouteImport } from './routes/teams/$id/index'
import { Route as AgentsIdIndexRouteImport } from './routes/agents/$id/index'
import { Route as TeamsIdPolicyRouteImport } from './routes/teams/$id/policy'
import { Route as TeamsIdMemoryRouteImport } from './routes/teams/$id/memory'
import { Route as TeamsIdMembersRouteImport } from './routes/teams/$id/members'
import { Route as TeamsIdContextRouteImport } from './routes/teams/$id/context'
import { Route as TeamsIdActivityRouteImport } from './routes/teams/$id/activity'
import { Route as ConfigIntegrationsTelegramRouteImport } from './routes/config/integrations/telegram'
import { Route as AgentsIdTriggersRouteImport } from './routes/agents/$id/triggers'
import { Route as AgentsIdLearningRouteImport } from './routes/agents/$id/learning'
import { Route as AgentsIdInboxRouteImport } from './routes/agents/$id/inbox'
import { Route as TemplatesTeamsIdIndexRouteImport } from './routes/templates/teams/$id/index'
import { Route as TemplatesAgentsIdIndexRouteImport } from './routes/templates/agents/$id/index'

const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesIndexRoute = TemplatesIndexRouteImport.update({
  id: '/templates/',
  path: '/templates/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamsIndexRoute = TeamsIndexRouteImport.update({
  id: '/teams/',
  path: '/teams/',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillsIndexRoute = SkillsIndexRouteImport.update({
  id: '/skills/',
  path: '/skills/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfigIndexRoute = ConfigIndexRouteImport.update({
  id: '/config/',
  path: '/config/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApprovalsIndexRoute = ApprovalsIndexRouteImport.update({
  id: '/approvals/',
  path: '/approvals/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsIndexRoute = AgentsIndexRouteImport.update({
  id: '/agents/',
  path: '/agents/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfigTokensRoute = ConfigTokensRouteImport.update({
  id: '/config/tokens',
  path: '/config/tokens',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfigServicesRoute = ConfigServicesRouteImport.update({
  id: '/config/services',
  path: '/config/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfigMcpRoute = ConfigMcpRouteImport.update({
  id: '/config/mcp',
  path: '/config/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesTeamsIndexRoute = TemplatesTeamsIndexRouteImport.update({
  id: '/templates/teams/',
  path: '/templates/teams/',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesAgentsIndexRoute = TemplatesAgentsIndexRouteImport.update({
  id: '/templates/agents/',
  path: '/templates/agents/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamsIdIndexRoute = TeamsIdIndexRouteImport.update({
  id: '/teams/$id/',
  path: '/teams/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsIdIndexRoute = AgentsIdIndexRouteImport.update({
  id: '/agents/$id/',
  path: '/agents/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamsIdPolicyRoute = TeamsIdPolicyRouteImport.update({
  id: '/teams/$id/policy',
  path: '/teams/$id/policy',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamsIdMemoryRoute = TeamsIdMemoryRouteImport.update({
  id: '/teams/$id/memory',
  path: '/teams/$id/memory',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamsIdMembersRoute = TeamsIdMembersRouteImport.update({
  id: '/teams/$id/members',
  path: '/teams/$id/members',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamsIdContextRoute = TeamsIdContextRouteImport.update({
  id: '/teams/$id/context',
  path: '/teams/$id/context',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamsIdActivityRoute = TeamsIdActivityRouteImport.update({
  id: '/teams/$id/activity',
  path: '/teams/$id/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfigIntegrationsTelegramRoute =
  ConfigIntegrationsTelegramRouteImport.update({
    id: '/config/integrations/telegram',
    path: '/config/integrations/telegram',
    getParentRoute: () => rootRouteImport,
  } as any)
const AgentsIdTriggersRoute = AgentsIdTriggersRouteImport.update({
  id: '/agents/$id/triggers',
  path: '/agents/$id/triggers',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsIdLearningRoute = AgentsIdLearningRouteImport.update({
  id: '/agents/$id/learning',
  path: '/agents/$id/learning',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsIdInboxRoute = AgentsIdInboxRouteImport.update({
  id: '/agents/$id/inbox',
  path: '/agents/$id/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesTeamsIdIndexRoute = TemplatesTeamsIdIndexRouteImport.update({
  id: '/templates/teams/$id/',
  path: '/templates/teams/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesAgentsIdIndexRoute = TemplatesAgentsIdIndexRouteImport.update({
  id: '/templates/agents/$id/',
  path: '/templates/agents/$id/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/welcome': typeof WelcomeRoute
  '/api/$': typeof ApiSplatRoute
  '/config/mcp': typeof ConfigMcpRoute
  '/config/services': typeof ConfigServicesRoute
  '/config/tokens': typeof ConfigTokensRoute
  '/agents/': typeof AgentsIndexRoute
  '/approvals/': typeof ApprovalsIndexRoute
  '/config/': typeof ConfigIndexRoute
  '/skills/': typeof SkillsIndexRoute
  '/teams/': typeof TeamsIndexRoute
  '/templates/': typeof TemplatesIndexRoute
  '/agents/$id/inbox': typeof AgentsIdInboxRoute
  '/agents/$id/learning': typeof AgentsIdLearningRoute
  '/agents/$id/triggers': typeof AgentsIdTriggersRoute
  '/config/integrations/telegram': typeof ConfigIntegrationsTelegramRoute
  '/teams/$id/activity': typeof TeamsIdActivityRoute
  '/teams/$id/context': typeof TeamsIdContextRoute
  '/teams/$id/members': typeof TeamsIdMembersRoute
  '/teams/$id/memory': typeof TeamsIdMemoryRoute
  '/teams/$id/policy': typeof TeamsIdPolicyRoute
  '/agents/$id/': typeof AgentsIdIndexRoute
  '/teams/$id/': typeof TeamsIdIndexRoute
  '/templates/agents/': typeof TemplatesAgentsIndexRoute
  '/templates/teams/': typeof TemplatesTeamsIndexRoute
  '/templates/agents/$id/': typeof TemplatesAgentsIdIndexRoute
  '/templates/teams/$id/': typeof TemplatesTeamsIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/welcome': typeof WelcomeRoute
  '/api/$': typeof ApiSplatRoute
  '/config/mcp': typeof ConfigMcpRoute
  '/config/services': typeof ConfigServicesRoute
  '/config/tokens': typeof ConfigTokensRoute
  '/agents': typeof AgentsIndexRoute
  '/approvals': typeof ApprovalsIndexRoute
  '/config': typeof ConfigIndexRoute
  '/skills': typeof SkillsIndexRoute
  '/teams': typeof TeamsIndexRoute
  '/templates': typeof TemplatesIndexRoute
  '/agents/$id/inbox': typeof AgentsIdInboxRoute
  '/agents/$id/learning': typeof AgentsIdLearningRoute
  '/agents/$id/triggers': typeof AgentsIdTriggersRoute
  '/config/integrations/telegram': typeof ConfigIntegrationsTelegramRoute
  '/teams/$id/activity': typeof TeamsIdActivityRoute
  '/teams/$id/context': typeof TeamsIdContextRoute
  '/teams/$id/members': typeof TeamsIdMembersRoute
  '/teams/$id/memory': typeof TeamsIdMemoryRoute
  '/teams/$id/policy': typeof TeamsIdPolicyRoute
  '/agents/$id': typeof AgentsIdIndexRoute
  '/teams/$id': typeof TeamsIdIndexRoute
  '/templates/agents': typeof TemplatesAgentsIndexRoute
  '/templates/teams': typeof TemplatesTeamsIndexRoute
  '/templates/agents/$id': typeof TemplatesAgentsIdIndexRoute
  '/templates/teams/$id': typeof TemplatesTeamsIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/welcome': typeof WelcomeRoute
  '/api/$': typeof ApiSplatRoute
  '/config/mcp': typeof ConfigMcpRoute
  '/config/services': typeof ConfigServicesRoute
  '/config/tokens': typeof ConfigTokensRoute
  '/agents/': typeof AgentsIndexRoute
  '/approvals/': typeof ApprovalsIndexRoute
  '/config/': typeof ConfigIndexRoute
  '/skills/': typeof SkillsIndexRoute
  '/teams/': typeof TeamsIndexRoute
  '/templates/': typeof TemplatesIndexRoute
  '/agents/$id/inbox': typeof AgentsIdInboxRoute
  '/agents/$id/learning': typeof AgentsIdLearningRoute
  '/agents/$id/triggers': typeof AgentsIdTriggersRoute
  '/config/integrations/telegram': typeof ConfigIntegrationsTelegramRoute
  '/teams/$id/activity': typeof TeamsIdActivityRoute
  '/teams/$id/context': typeof TeamsIdContextRoute
  '/teams/$id/members': typeof TeamsIdMembersRoute
  '/teams/$id/memory': typeof TeamsIdMemoryRoute
  '/teams/$id/policy': typeof TeamsIdPolicyRoute
  '/agents/$id/': typeof AgentsIdIndexRoute
  '/teams/$id/': typeof TeamsIdIndexRoute
  '/templates/agents/': typeof TemplatesAgentsIndexRoute
  '/templates/teams/': typeof TemplatesTeamsIndexRoute
  '/templates/agents/$id/': typeof TemplatesAgentsIdIndexRoute
  '/templates/teams/$id/': typeof TemplatesTeamsIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/welcome'
    | '/api/$'
    | '/config/mcp'
    | '/config/services'
    | '/config/tokens'
    | '/agents/'
    | '/approvals/'
    | '/config/'
    | '/skills/'
    | '/teams/'
    | '/templates/'
    | '/agents/$id/inbox'
    | '/agents/$id/learning'
    | '/agents/$id/triggers'
    | '/config/integrations/telegram'
    | '/teams/$id/activity'
    | '/teams/$id/context'
    | '/teams/$id/members'
    | '/teams/$id/memory'
    | '/teams/$id/policy'
    | '/agents/$id/'
    | '/teams/$id/'
    | '/templates/agents/'
    | '/templates/teams/'
    | '/templates/agents/$id/'
    | '/templates/teams/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/welcome'
    | '/api/$'
    | '/config/mcp'
    | '/config/services'
    | '/config/tokens'
    | '/agents'
    | '/approvals'
    | '/config'
    | '/skills'
    | '/teams'
    | '/templates'
    | '/agents/$id/inbox'
    | '/agents/$id/learning'
    | '/agents/$id/triggers'
    | '/config/integrations/telegram'
    | '/teams/$id/activity'
    | '/teams/$id/context'
    | '/teams/$id/members'
    | '/teams/$id/memory'
    | '/teams/$id/policy'
    | '/agents/$id'
    | '/teams/$id'
    | '/templates/agents'
    | '/templates/teams'
    | '/templates/agents/$id'
    | '/templates/teams/$id'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/welcome'
    | '/api/$'
    | '/config/mcp'
    | '/config/services'
    | '/config/tokens'
    | '/agents/'
    | '/approvals/'
    | '/config/'
    | '/skills/'
    | '/teams/'
    | '/templates/'
    | '/agents/$id/inbox'
    | '/agents/$id/learning'
    | '/agents/$id/triggers'
    | '/config/integrations/telegram'
    | '/teams/$id/activity'
    | '/teams/$id/context'
    | '/teams/$id/members'
    | '/teams/$id/memory'
    | '/teams/$id/policy'
    | '/agents/$id/'
    | '/teams/$id/'
    | '/templates/agents/'
    | '/templates/teams/'
    | '/templates/agents/$id/'
    | '/templates/teams/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  WelcomeRoute: typeof WelcomeRoute
  ApiSplatRoute: typeof ApiSplatRoute
  ConfigMcpRoute: typeof ConfigMcpRoute
  ConfigServicesRoute: typeof ConfigServicesRoute
  ConfigTokensRoute: typeof ConfigTokensRoute
  AgentsIndexRoute: typeof AgentsIndexRoute
  ApprovalsIndexRoute: typeof ApprovalsIndexRoute
  ConfigIndexRoute: typeof ConfigIndexRoute
  SkillsIndexRoute: typeof SkillsIndexRoute
  TeamsIndexRoute: typeof TeamsIndexRoute
  TemplatesIndexRoute: typeof TemplatesIndexRoute
  AgentsIdInboxRoute: typeof AgentsIdInboxRoute
  AgentsIdLearningRoute: typeof AgentsIdLearningRoute
  AgentsIdTriggersRoute: typeof AgentsIdTriggersRoute
  ConfigIntegrationsTelegramRoute: typeof ConfigIntegrationsTelegramRoute
  TeamsIdActivityRoute: typeof TeamsIdActivityRoute
  TeamsIdContextRoute: typeof TeamsIdContextRoute
  TeamsIdMembersRoute: typeof TeamsIdMembersRoute
  TeamsIdMemoryRoute: typeof TeamsIdMemoryRoute
  TeamsIdPolicyRoute: typeof TeamsIdPolicyRoute
  AgentsIdIndexRoute: typeof AgentsIdIndexRoute
  TeamsIdIndexRoute: typeof TeamsIdIndexRoute
  TemplatesAgentsIndexRoute: typeof TemplatesAgentsIndexRoute
  TemplatesTeamsIndexRoute: typeof TemplatesTeamsIndexRoute
  TemplatesAgentsIdIndexRoute: typeof TemplatesAgentsIdIndexRoute
  TemplatesTeamsIdIndexRoute: typeof TemplatesTeamsIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates/': {
      id: '/templates/'
      path: '/templates'
      fullPath: '/templates/'
      preLoaderRoute: typeof TemplatesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams/': {
      id: '/teams/'
      path: '/teams'
      fullPath: '/teams/'
      preLoaderRoute: typeof TeamsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skills/': {
      id: '/skills/'
      path: '/skills'
      fullPath: '/skills/'
      preLoaderRoute: typeof SkillsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/config/': {
      id: '/config/'
      path: '/config'
      fullPath: '/config/'
      preLoaderRoute: typeof ConfigIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/approvals/': {
      id: '/approvals/'
      path: '/approvals'
      fullPath: '/approvals/'
      preLoaderRoute: typeof ApprovalsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/': {
      id: '/agents/'
      path: '/agents'
      fullPath: '/agents/'
      preLoaderRoute: typeof AgentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/config/tokens': {
      id: '/config/tokens'
      path: '/config/tokens'
      fullPath: '/config/tokens'
      preLoaderRoute: typeof ConfigTokensRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/config/services': {
      id: '/config/services'
      path: '/config/services'
      fullPath: '/config/services'
      preLoaderRoute: typeof ConfigServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/config/mcp': {
      id: '/config/mcp'
      path: '/config/mcp'
      fullPath: '/config/mcp'
      preLoaderRoute: typeof ConfigMcpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates/teams/': {
      id: '/templates/teams/'
      path: '/templates/teams'
      fullPath: '/templates/teams/'
      preLoaderRoute: typeof TemplatesTeamsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates/agents/': {
      id: '/templates/agents/'
      path: '/templates/agents'
      fullPath: '/templates/agents/'
      preLoaderRoute: typeof TemplatesAgentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams/$id/': {
      id: '/teams/$id/'
      path: '/teams/$id'
      fullPath: '/teams/$id/'
      preLoaderRoute: typeof TeamsIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/$id/': {
      id: '/agents/$id/'
      path: '/agents/$id'
      fullPath: '/agents/$id/'
      preLoaderRoute: typeof AgentsIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams/$id/policy': {
      id: '/teams/$id/policy'
      path: '/teams/$id/policy'
      fullPath: '/teams/$id/policy'
      preLoaderRoute: typeof TeamsIdPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams/$id/memory': {
      id: '/teams/$id/memory'
      path: '/teams/$id/memory'
      fullPath: '/teams/$id/memory'
      preLoaderRoute: typeof TeamsIdMemoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams/$id/members': {
      id: '/teams/$id/members'
      path: '/teams/$id/members'
      fullPath: '/teams/$id/members'
      preLoaderRoute: typeof TeamsIdMembersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams/$id/context': {
      id: '/teams/$id/context'
      path: '/teams/$id/context'
      fullPath: '/teams/$id/context'
      preLoaderRoute: typeof TeamsIdContextRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams/$id/activity': {
      id: '/teams/$id/activity'
      path: '/teams/$id/activity'
      fullPath: '/teams/$id/activity'
      preLoaderRoute: typeof TeamsIdActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/config/integrations/telegram': {
      id: '/config/integrations/telegram'
      path: '/config/integrations/telegram'
      fullPath: '/config/integrations/telegram'
      preLoaderRoute: typeof ConfigIntegrationsTelegramRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/$id/triggers': {
      id: '/agents/$id/triggers'
      path: '/agents/$id/triggers'
      fullPath: '/agents/$id/triggers'
      preLoaderRoute: typeof AgentsIdTriggersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/$id/learning': {
      id: '/agents/$id/learning'
      path: '/agents/$id/learning'
      fullPath: '/agents/$id/learning'
      preLoaderRoute: typeof AgentsIdLearningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/$id/inbox': {
      id: '/agents/$id/inbox'
      path: '/agents/$id/inbox'
      fullPath: '/agents/$id/inbox'
      preLoaderRoute: typeof AgentsIdInboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates/teams/$id/': {
      id: '/templates/teams/$id/'
      path: '/templates/teams/$id'
      fullPath: '/templates/teams/$id/'
      preLoaderRoute: typeof TemplatesTeamsIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates/agents/$id/': {
      id: '/templates/agents/$id/'
      path: '/templates/agents/$id'
      fullPath: '/templates/agents/$id/'
      preLoaderRoute: typeof TemplatesAgentsIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  WelcomeRoute: WelcomeRoute,
  ApiSplatRoute: ApiSplatRoute,
  ConfigMcpRoute: ConfigMcpRoute,
  ConfigServicesRoute: ConfigServicesRoute,
  ConfigTokensRoute: ConfigTokensRoute,
  AgentsIndexRoute: AgentsIndexRoute,
  ApprovalsIndexRoute: ApprovalsIndexRoute,
  ConfigIndexRoute: ConfigIndexRoute,
  SkillsIndexRoute: SkillsIndexRoute,
  TeamsIndexRoute: TeamsIndexRoute,
  TemplatesIndexRoute: TemplatesIndexRoute,
  AgentsIdInboxRoute: AgentsIdInboxRoute,
  AgentsIdLearningRoute: AgentsIdLearningRoute,
  AgentsIdTriggersRoute: AgentsIdTriggersRoute,
  ConfigIntegrationsTelegramRoute: ConfigIntegrationsTelegramRoute,
  TeamsIdActivityRoute: TeamsIdActivityRoute,
  TeamsIdContextRoute: TeamsIdContextRoute,
  TeamsIdMembersRoute: TeamsIdMembersRoute,
  TeamsIdMemoryRoute: TeamsIdMemoryRoute,
  TeamsIdPolicyRoute: TeamsIdPolicyRoute,
  AgentsIdIndexRoute: AgentsIdIndexRoute,
  TeamsIdIndexRoute: TeamsIdIndexRoute,
  TemplatesAgentsIndexRoute: TemplatesAgentsIndexRoute,
  TemplatesTeamsIndexRoute: TemplatesTeamsIndexRoute,
  TemplatesAgentsIdIndexRoute: TemplatesAgentsIdIndexRoute,
  TemplatesTeamsIdIndexRoute: TemplatesTeamsIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
