/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TemplatesIndexRouteImport } from './routes/templates/index'
import { Route as SkillsIndexRouteImport } from './routes/skills/index'
import { Route as ProfilesIndexRouteImport } from './routes/profiles/index'
import { Route as ProfileGroupsIndexRouteImport } from './routes/profile-groups/index'
import { Route as HarnessesIndexRouteImport } from './routes/harnesses/index'
import { Route as GroupsIndexRouteImport } from './routes/groups/index'
import { Route as ConfigIndexRouteImport } from './routes/config/index'
import { Route as ApprovalsIndexRouteImport } from './routes/approvals/index'
import { Route as AgentsIndexRouteImport } from './routes/agents/index'
import { Route as ProfilesIdRouteImport } from './routes/profiles/$id'
import { Route as ProfileGroupsIdRouteImport } from './routes/profile-groups/$id'
import { Route as HarnessesIdRouteImport } from './routes/harnesses/$id'
import { Route as ConfigTokensRouteImport } from './routes/config/tokens'
import { Route as ConfigServicesRouteImport } from './routes/config/services'
import { Route as ConfigMcpRouteImport } from './routes/config/mcp'
import { Route as ApiSplatRouteImport } from './routes/api/$'
import { Route as TemplatesTeamsIndexRouteImport } from './routes/templates/teams/index'
import { Route as TemplatesAgentsIndexRouteImport } from './routes/templates/agents/index'
import { Route as GroupsIdIndexRouteImport } from './routes/groups/$id/index'
import { Route as AgentsIdIndexRouteImport } from './routes/agents/$id/index'
import { Route as GroupsIdPolicyRouteImport } from './routes/groups/$id/policy'
import { Route as GroupsIdMemoryRouteImport } from './routes/groups/$id/memory'
import { Route as GroupsIdMembersRouteImport } from './routes/groups/$id/members'
import { Route as GroupsIdContextRouteImport } from './routes/groups/$id/context'
import { Route as GroupsIdActivityRouteImport } from './routes/groups/$id/activity'
import { Route as ConfigIntegrationsTelegramRouteImport } from './routes/config/integrations/telegram'
import { Route as AgentsIdTriggersRouteImport } from './routes/agents/$id/triggers'
import { Route as AgentsIdInboxRouteImport } from './routes/agents/$id/inbox'
import { Route as TemplatesTeamsIdIndexRouteImport } from './routes/templates/teams/$id/index'
import { Route as TemplatesAgentsIdIndexRouteImport } from './routes/templates/agents/$id/index'

const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesIndexRoute = TemplatesIndexRouteImport.update({
  id: '/templates/',
  path: '/templates/',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillsIndexRoute = SkillsIndexRouteImport.update({
  id: '/skills/',
  path: '/skills/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilesIndexRoute = ProfilesIndexRouteImport.update({
  id: '/profiles/',
  path: '/profiles/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileGroupsIndexRoute = ProfileGroupsIndexRouteImport.update({
  id: '/profile-groups/',
  path: '/profile-groups/',
  getParentRoute: () => rootRouteImport,
} as any)
const HarnessesIndexRoute = HarnessesIndexRouteImport.update({
  id: '/harnesses/',
  path: '/harnesses/',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupsIndexRoute = GroupsIndexRouteImport.update({
  id: '/groups/',
  path: '/groups/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfigIndexRoute = ConfigIndexRouteImport.update({
  id: '/config/',
  path: '/config/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApprovalsIndexRoute = ApprovalsIndexRouteImport.update({
  id: '/approvals/',
  path: '/approvals/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsIndexRoute = AgentsIndexRouteImport.update({
  id: '/agents/',
  path: '/agents/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilesIdRoute = ProfilesIdRouteImport.update({
  id: '/profiles/$id',
  path: '/profiles/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileGroupsIdRoute = ProfileGroupsIdRouteImport.update({
  id: '/profile-groups/$id',
  path: '/profile-groups/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const HarnessesIdRoute = HarnessesIdRouteImport.update({
  id: '/harnesses/$id',
  path: '/harnesses/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfigTokensRoute = ConfigTokensRouteImport.update({
  id: '/config/tokens',
  path: '/config/tokens',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfigServicesRoute = ConfigServicesRouteImport.update({
  id: '/config/services',
  path: '/config/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfigMcpRoute = ConfigMcpRouteImport.update({
  id: '/config/mcp',
  path: '/config/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesTeamsIndexRoute = TemplatesTeamsIndexRouteImport.update({
  id: '/templates/teams/',
  path: '/templates/teams/',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesAgentsIndexRoute = TemplatesAgentsIndexRouteImport.update({
  id: '/templates/agents/',
  path: '/templates/agents/',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupsIdIndexRoute = GroupsIdIndexRouteImport.update({
  id: '/groups/$id/',
  path: '/groups/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsIdIndexRoute = AgentsIdIndexRouteImport.update({
  id: '/agents/$id/',
  path: '/agents/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupsIdPolicyRoute = GroupsIdPolicyRouteImport.update({
  id: '/groups/$id/policy',
  path: '/groups/$id/policy',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupsIdMemoryRoute = GroupsIdMemoryRouteImport.update({
  id: '/groups/$id/memory',
  path: '/groups/$id/memory',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupsIdMembersRoute = GroupsIdMembersRouteImport.update({
  id: '/groups/$id/members',
  path: '/groups/$id/members',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupsIdContextRoute = GroupsIdContextRouteImport.update({
  id: '/groups/$id/context',
  path: '/groups/$id/context',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupsIdActivityRoute = GroupsIdActivityRouteImport.update({
  id: '/groups/$id/activity',
  path: '/groups/$id/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfigIntegrationsTelegramRoute =
  ConfigIntegrationsTelegramRouteImport.update({
    id: '/config/integrations/telegram',
    path: '/config/integrations/telegram',
    getParentRoute: () => rootRouteImport,
  } as any)
const AgentsIdTriggersRoute = AgentsIdTriggersRouteImport.update({
  id: '/agents/$id/triggers',
  path: '/agents/$id/triggers',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsIdInboxRoute = AgentsIdInboxRouteImport.update({
  id: '/agents/$id/inbox',
  path: '/agents/$id/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesTeamsIdIndexRoute = TemplatesTeamsIdIndexRouteImport.update({
  id: '/templates/teams/$id/',
  path: '/templates/teams/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesAgentsIdIndexRoute = TemplatesAgentsIdIndexRouteImport.update({
  id: '/templates/agents/$id/',
  path: '/templates/agents/$id/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/welcome': typeof WelcomeRoute
  '/api/$': typeof ApiSplatRoute
  '/config/mcp': typeof ConfigMcpRoute
  '/config/services': typeof ConfigServicesRoute
  '/config/tokens': typeof ConfigTokensRoute
  '/harnesses/$id': typeof HarnessesIdRoute
  '/profile-groups/$id': typeof ProfileGroupsIdRoute
  '/profiles/$id': typeof ProfilesIdRoute
  '/agents/': typeof AgentsIndexRoute
  '/approvals/': typeof ApprovalsIndexRoute
  '/config/': typeof ConfigIndexRoute
  '/groups/': typeof GroupsIndexRoute
  '/harnesses/': typeof HarnessesIndexRoute
  '/profile-groups/': typeof ProfileGroupsIndexRoute
  '/profiles/': typeof ProfilesIndexRoute
  '/skills/': typeof SkillsIndexRoute
  '/templates/': typeof TemplatesIndexRoute
  '/agents/$id/inbox': typeof AgentsIdInboxRoute
  '/agents/$id/triggers': typeof AgentsIdTriggersRoute
  '/config/integrations/telegram': typeof ConfigIntegrationsTelegramRoute
  '/groups/$id/activity': typeof GroupsIdActivityRoute
  '/groups/$id/context': typeof GroupsIdContextRoute
  '/groups/$id/members': typeof GroupsIdMembersRoute
  '/groups/$id/memory': typeof GroupsIdMemoryRoute
  '/groups/$id/policy': typeof GroupsIdPolicyRoute
  '/agents/$id/': typeof AgentsIdIndexRoute
  '/groups/$id/': typeof GroupsIdIndexRoute
  '/templates/agents/': typeof TemplatesAgentsIndexRoute
  '/templates/teams/': typeof TemplatesTeamsIndexRoute
  '/templates/agents/$id/': typeof TemplatesAgentsIdIndexRoute
  '/templates/teams/$id/': typeof TemplatesTeamsIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/welcome': typeof WelcomeRoute
  '/api/$': typeof ApiSplatRoute
  '/config/mcp': typeof ConfigMcpRoute
  '/config/services': typeof ConfigServicesRoute
  '/config/tokens': typeof ConfigTokensRoute
  '/harnesses/$id': typeof HarnessesIdRoute
  '/profile-groups/$id': typeof ProfileGroupsIdRoute
  '/profiles/$id': typeof ProfilesIdRoute
  '/agents': typeof AgentsIndexRoute
  '/approvals': typeof ApprovalsIndexRoute
  '/config': typeof ConfigIndexRoute
  '/groups': typeof GroupsIndexRoute
  '/harnesses': typeof HarnessesIndexRoute
  '/profile-groups': typeof ProfileGroupsIndexRoute
  '/profiles': typeof ProfilesIndexRoute
  '/skills': typeof SkillsIndexRoute
  '/templates': typeof TemplatesIndexRoute
  '/agents/$id/inbox': typeof AgentsIdInboxRoute
  '/agents/$id/triggers': typeof AgentsIdTriggersRoute
  '/config/integrations/telegram': typeof ConfigIntegrationsTelegramRoute
  '/groups/$id/activity': typeof GroupsIdActivityRoute
  '/groups/$id/context': typeof GroupsIdContextRoute
  '/groups/$id/members': typeof GroupsIdMembersRoute
  '/groups/$id/memory': typeof GroupsIdMemoryRoute
  '/groups/$id/policy': typeof GroupsIdPolicyRoute
  '/agents/$id': typeof AgentsIdIndexRoute
  '/groups/$id': typeof GroupsIdIndexRoute
  '/templates/agents': typeof TemplatesAgentsIndexRoute
  '/templates/teams': typeof TemplatesTeamsIndexRoute
  '/templates/agents/$id': typeof TemplatesAgentsIdIndexRoute
  '/templates/teams/$id': typeof TemplatesTeamsIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/welcome': typeof WelcomeRoute
  '/api/$': typeof ApiSplatRoute
  '/config/mcp': typeof ConfigMcpRoute
  '/config/services': typeof ConfigServicesRoute
  '/config/tokens': typeof ConfigTokensRoute
  '/harnesses/$id': typeof HarnessesIdRoute
  '/profile-groups/$id': typeof ProfileGroupsIdRoute
  '/profiles/$id': typeof ProfilesIdRoute
  '/agents/': typeof AgentsIndexRoute
  '/approvals/': typeof ApprovalsIndexRoute
  '/config/': typeof ConfigIndexRoute
  '/groups/': typeof GroupsIndexRoute
  '/harnesses/': typeof HarnessesIndexRoute
  '/profile-groups/': typeof ProfileGroupsIndexRoute
  '/profiles/': typeof ProfilesIndexRoute
  '/skills/': typeof SkillsIndexRoute
  '/templates/': typeof TemplatesIndexRoute
  '/agents/$id/inbox': typeof AgentsIdInboxRoute
  '/agents/$id/triggers': typeof AgentsIdTriggersRoute
  '/config/integrations/telegram': typeof ConfigIntegrationsTelegramRoute
  '/groups/$id/activity': typeof GroupsIdActivityRoute
  '/groups/$id/context': typeof GroupsIdContextRoute
  '/groups/$id/members': typeof GroupsIdMembersRoute
  '/groups/$id/memory': typeof GroupsIdMemoryRoute
  '/groups/$id/policy': typeof GroupsIdPolicyRoute
  '/agents/$id/': typeof AgentsIdIndexRoute
  '/groups/$id/': typeof GroupsIdIndexRoute
  '/templates/agents/': typeof TemplatesAgentsIndexRoute
  '/templates/teams/': typeof TemplatesTeamsIndexRoute
  '/templates/agents/$id/': typeof TemplatesAgentsIdIndexRoute
  '/templates/teams/$id/': typeof TemplatesTeamsIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/welcome'
    | '/api/$'
    | '/config/mcp'
    | '/config/services'
    | '/config/tokens'
    | '/harnesses/$id'
    | '/profile-groups/$id'
    | '/profiles/$id'
    | '/agents/'
    | '/approvals/'
    | '/config/'
    | '/groups/'
    | '/harnesses/'
    | '/profile-groups/'
    | '/profiles/'
    | '/skills/'
    | '/templates/'
    | '/agents/$id/inbox'
    | '/agents/$id/triggers'
    | '/config/integrations/telegram'
    | '/groups/$id/activity'
    | '/groups/$id/context'
    | '/groups/$id/members'
    | '/groups/$id/memory'
    | '/groups/$id/policy'
    | '/agents/$id/'
    | '/groups/$id/'
    | '/templates/agents/'
    | '/templates/teams/'
    | '/templates/agents/$id/'
    | '/templates/teams/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/welcome'
    | '/api/$'
    | '/config/mcp'
    | '/config/services'
    | '/config/tokens'
    | '/harnesses/$id'
    | '/profile-groups/$id'
    | '/profiles/$id'
    | '/agents'
    | '/approvals'
    | '/config'
    | '/groups'
    | '/harnesses'
    | '/profile-groups'
    | '/profiles'
    | '/skills'
    | '/templates'
    | '/agents/$id/inbox'
    | '/agents/$id/triggers'
    | '/config/integrations/telegram'
    | '/groups/$id/activity'
    | '/groups/$id/context'
    | '/groups/$id/members'
    | '/groups/$id/memory'
    | '/groups/$id/policy'
    | '/agents/$id'
    | '/groups/$id'
    | '/templates/agents'
    | '/templates/teams'
    | '/templates/agents/$id'
    | '/templates/teams/$id'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/welcome'
    | '/api/$'
    | '/config/mcp'
    | '/config/services'
    | '/config/tokens'
    | '/harnesses/$id'
    | '/profile-groups/$id'
    | '/profiles/$id'
    | '/agents/'
    | '/approvals/'
    | '/config/'
    | '/groups/'
    | '/harnesses/'
    | '/profile-groups/'
    | '/profiles/'
    | '/skills/'
    | '/templates/'
    | '/agents/$id/inbox'
    | '/agents/$id/triggers'
    | '/config/integrations/telegram'
    | '/groups/$id/activity'
    | '/groups/$id/context'
    | '/groups/$id/members'
    | '/groups/$id/memory'
    | '/groups/$id/policy'
    | '/agents/$id/'
    | '/groups/$id/'
    | '/templates/agents/'
    | '/templates/teams/'
    | '/templates/agents/$id/'
    | '/templates/teams/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  WelcomeRoute: typeof WelcomeRoute
  ApiSplatRoute: typeof ApiSplatRoute
  ConfigMcpRoute: typeof ConfigMcpRoute
  ConfigServicesRoute: typeof ConfigServicesRoute
  ConfigTokensRoute: typeof ConfigTokensRoute
  HarnessesIdRoute: typeof HarnessesIdRoute
  ProfileGroupsIdRoute: typeof ProfileGroupsIdRoute
  ProfilesIdRoute: typeof ProfilesIdRoute
  AgentsIndexRoute: typeof AgentsIndexRoute
  ApprovalsIndexRoute: typeof ApprovalsIndexRoute
  ConfigIndexRoute: typeof ConfigIndexRoute
  GroupsIndexRoute: typeof GroupsIndexRoute
  HarnessesIndexRoute: typeof HarnessesIndexRoute
  ProfileGroupsIndexRoute: typeof ProfileGroupsIndexRoute
  ProfilesIndexRoute: typeof ProfilesIndexRoute
  SkillsIndexRoute: typeof SkillsIndexRoute
  TemplatesIndexRoute: typeof TemplatesIndexRoute
  AgentsIdInboxRoute: typeof AgentsIdInboxRoute
  AgentsIdTriggersRoute: typeof AgentsIdTriggersRoute
  ConfigIntegrationsTelegramRoute: typeof ConfigIntegrationsTelegramRoute
  GroupsIdActivityRoute: typeof GroupsIdActivityRoute
  GroupsIdContextRoute: typeof GroupsIdContextRoute
  GroupsIdMembersRoute: typeof GroupsIdMembersRoute
  GroupsIdMemoryRoute: typeof GroupsIdMemoryRoute
  GroupsIdPolicyRoute: typeof GroupsIdPolicyRoute
  AgentsIdIndexRoute: typeof AgentsIdIndexRoute
  GroupsIdIndexRoute: typeof GroupsIdIndexRoute
  TemplatesAgentsIndexRoute: typeof TemplatesAgentsIndexRoute
  TemplatesTeamsIndexRoute: typeof TemplatesTeamsIndexRoute
  TemplatesAgentsIdIndexRoute: typeof TemplatesAgentsIdIndexRoute
  TemplatesTeamsIdIndexRoute: typeof TemplatesTeamsIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates/': {
      id: '/templates/'
      path: '/templates'
      fullPath: '/templates/'
      preLoaderRoute: typeof TemplatesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skills/': {
      id: '/skills/'
      path: '/skills'
      fullPath: '/skills/'
      preLoaderRoute: typeof SkillsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profiles/': {
      id: '/profiles/'
      path: '/profiles'
      fullPath: '/profiles/'
      preLoaderRoute: typeof ProfilesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile-groups/': {
      id: '/profile-groups/'
      path: '/profile-groups'
      fullPath: '/profile-groups/'
      preLoaderRoute: typeof ProfileGroupsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/harnesses/': {
      id: '/harnesses/'
      path: '/harnesses'
      fullPath: '/harnesses/'
      preLoaderRoute: typeof HarnessesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups/': {
      id: '/groups/'
      path: '/groups'
      fullPath: '/groups/'
      preLoaderRoute: typeof GroupsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/config/': {
      id: '/config/'
      path: '/config'
      fullPath: '/config/'
      preLoaderRoute: typeof ConfigIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/approvals/': {
      id: '/approvals/'
      path: '/approvals'
      fullPath: '/approvals/'
      preLoaderRoute: typeof ApprovalsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/': {
      id: '/agents/'
      path: '/agents'
      fullPath: '/agents/'
      preLoaderRoute: typeof AgentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profiles/$id': {
      id: '/profiles/$id'
      path: '/profiles/$id'
      fullPath: '/profiles/$id'
      preLoaderRoute: typeof ProfilesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile-groups/$id': {
      id: '/profile-groups/$id'
      path: '/profile-groups/$id'
      fullPath: '/profile-groups/$id'
      preLoaderRoute: typeof ProfileGroupsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/harnesses/$id': {
      id: '/harnesses/$id'
      path: '/harnesses/$id'
      fullPath: '/harnesses/$id'
      preLoaderRoute: typeof HarnessesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/config/tokens': {
      id: '/config/tokens'
      path: '/config/tokens'
      fullPath: '/config/tokens'
      preLoaderRoute: typeof ConfigTokensRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/config/services': {
      id: '/config/services'
      path: '/config/services'
      fullPath: '/config/services'
      preLoaderRoute: typeof ConfigServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/config/mcp': {
      id: '/config/mcp'
      path: '/config/mcp'
      fullPath: '/config/mcp'
      preLoaderRoute: typeof ConfigMcpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates/teams/': {
      id: '/templates/teams/'
      path: '/templates/teams'
      fullPath: '/templates/teams/'
      preLoaderRoute: typeof TemplatesTeamsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates/agents/': {
      id: '/templates/agents/'
      path: '/templates/agents'
      fullPath: '/templates/agents/'
      preLoaderRoute: typeof TemplatesAgentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups/$id/': {
      id: '/groups/$id/'
      path: '/groups/$id'
      fullPath: '/groups/$id/'
      preLoaderRoute: typeof GroupsIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/$id/': {
      id: '/agents/$id/'
      path: '/agents/$id'
      fullPath: '/agents/$id/'
      preLoaderRoute: typeof AgentsIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups/$id/policy': {
      id: '/groups/$id/policy'
      path: '/groups/$id/policy'
      fullPath: '/groups/$id/policy'
      preLoaderRoute: typeof GroupsIdPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups/$id/memory': {
      id: '/groups/$id/memory'
      path: '/groups/$id/memory'
      fullPath: '/groups/$id/memory'
      preLoaderRoute: typeof GroupsIdMemoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups/$id/members': {
      id: '/groups/$id/members'
      path: '/groups/$id/members'
      fullPath: '/groups/$id/members'
      preLoaderRoute: typeof GroupsIdMembersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups/$id/context': {
      id: '/groups/$id/context'
      path: '/groups/$id/context'
      fullPath: '/groups/$id/context'
      preLoaderRoute: typeof GroupsIdContextRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups/$id/activity': {
      id: '/groups/$id/activity'
      path: '/groups/$id/activity'
      fullPath: '/groups/$id/activity'
      preLoaderRoute: typeof GroupsIdActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/config/integrations/telegram': {
      id: '/config/integrations/telegram'
      path: '/config/integrations/telegram'
      fullPath: '/config/integrations/telegram'
      preLoaderRoute: typeof ConfigIntegrationsTelegramRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/$id/triggers': {
      id: '/agents/$id/triggers'
      path: '/agents/$id/triggers'
      fullPath: '/agents/$id/triggers'
      preLoaderRoute: typeof AgentsIdTriggersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/$id/inbox': {
      id: '/agents/$id/inbox'
      path: '/agents/$id/inbox'
      fullPath: '/agents/$id/inbox'
      preLoaderRoute: typeof AgentsIdInboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates/teams/$id/': {
      id: '/templates/teams/$id/'
      path: '/templates/teams/$id'
      fullPath: '/templates/teams/$id/'
      preLoaderRoute: typeof TemplatesTeamsIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates/agents/$id/': {
      id: '/templates/agents/$id/'
      path: '/templates/agents/$id'
      fullPath: '/templates/agents/$id/'
      preLoaderRoute: typeof TemplatesAgentsIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  WelcomeRoute: WelcomeRoute,
  ApiSplatRoute: ApiSplatRoute,
  ConfigMcpRoute: ConfigMcpRoute,
  ConfigServicesRoute: ConfigServicesRoute,
  ConfigTokensRoute: ConfigTokensRoute,
  HarnessesIdRoute: HarnessesIdRoute,
  ProfileGroupsIdRoute: ProfileGroupsIdRoute,
  ProfilesIdRoute: ProfilesIdRoute,
  AgentsIndexRoute: AgentsIndexRoute,
  ApprovalsIndexRoute: ApprovalsIndexRoute,
  ConfigIndexRoute: ConfigIndexRoute,
  GroupsIndexRoute: GroupsIndexRoute,
  HarnessesIndexRoute: HarnessesIndexRoute,
  ProfileGroupsIndexRoute: ProfileGroupsIndexRoute,
  ProfilesIndexRoute: ProfilesIndexRoute,
  SkillsIndexRoute: SkillsIndexRoute,
  TemplatesIndexRoute: TemplatesIndexRoute,
  AgentsIdInboxRoute: AgentsIdInboxRoute,
  AgentsIdTriggersRoute: AgentsIdTriggersRoute,
  ConfigIntegrationsTelegramRoute: ConfigIntegrationsTelegramRoute,
  GroupsIdActivityRoute: GroupsIdActivityRoute,
  GroupsIdContextRoute: GroupsIdContextRoute,
  GroupsIdMembersRoute: GroupsIdMembersRoute,
  GroupsIdMemoryRoute: GroupsIdMemoryRoute,
  GroupsIdPolicyRoute: GroupsIdPolicyRoute,
  AgentsIdIndexRoute: AgentsIdIndexRoute,
  GroupsIdIndexRoute: GroupsIdIndexRoute,
  TemplatesAgentsIndexRoute: TemplatesAgentsIndexRoute,
  TemplatesTeamsIndexRoute: TemplatesTeamsIndexRoute,
  TemplatesAgentsIdIndexRoute: TemplatesAgentsIdIndexRoute,
  TemplatesTeamsIdIndexRoute: TemplatesTeamsIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
